### PR TITLE
Test settings against Snapshot schema

### PR DESCRIPTION
**Pull request by fedgiac**
# Description
Validate the Snapshot settings schema as described [here](https://docs.snapshot.org/user-guides/spaces/create/alternative-way-to-create-a-space).

## How to test
CI.

### CODE REVIEW

**Comment by fedgiac** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfw78** [comment]
Just confirming that the method this is meant to test against is [here](https://github.com/snapshot-labs/snapshot.js/blob/a0adc547aa0922aa6abd35708a4a292048bca6a2/test/schema.ts#L4). In which case, I suspect that there may be a missing commit in the PR?

**Comment by fedgiac** [comment]
Yes, I forgot the actual change. :see_no_evil:

**Review by mfw78 — APPROVED** [review]
Great!

**Pull request merged**
